apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitlab.fullname" . }}
  labels:
    {{- include "gitlab.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gitlab.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gitlab.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - name: storage-data
          mountPath: /var/opt/gitlab
        - name: storage-config
          mountPath: /etc/gitlab
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: ssh
          containerPort: 22
          protocol: TCP
      volumes:
      - name: storage-data
        persistentVolumeClaim:
          claimName: {{ include "gitlab.storages.data.name" . }}
      - name: storage-config
        persistentVolumeClaim:
          claimName: {{ include "gitlab.storages.config.name" . }}
