apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitlab.storages.data.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.data.size | quote }}
  storageClassName: {{ include "gitlab.storages.data.name" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitlab.storages.config.name" . }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.config.size | quote }}
  storageClassName: {{ include "gitlab.storages.config.name" . }}
