replicaCount: 1

image:
  repository: localhost:32000/spice-html5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5959

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  hosts:
  - host: spice.example.local
    paths: [ "/" ]
  tls:
  - secretName: example-tls
    hosts:
    - spice.example.local

spice:
  host: vm.example.local
  port: 5900
