replicaCount: 1

image:
  repository: localhost:32000/code-server
  pullPolicy: IfNotPresent

services:
  http:
    type: ClusterIP
    port: 80
  dev:
    type: ClusterIP
    port: 3000

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
  hosts:
    http:
      host: code-server.example.local
      paths: [ "/" ]
    dev:
      host: code-server-dev.example.local
      paths: [ "/" ]
  tls:
  - secretName: example-tls
    hosts:
    - code-server.example.local
    - code-server-dev.example.local

storages:
  home:
    size: 10Gi
    path: <path to the directory>
    hostname: example
