replicaCount: 1

image:
  repository: localhost:32000/code-server
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
  hosts:
  - host: code-server.example.local
    paths: [ "/" ]
  tls:
  - secretName: example-tls
    hosts:
    - code-server.example.local

storages:
  home:
    size: 10Gi
    path: <path to the directory>
    hostname: example
