apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "openldap.storages.data.name" . }}
spec:
  capacity:
    storage: "{{ .Values.storages.data.size }}"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "openldap.storages.data.name" . }}
  local:
    path: {{ .Values.storages.data.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.data.hostname }}
