apiVersion: v1
kind: Service
metadata:
  name: {{ include "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.type }}
  ports:
  - port: {{ .Values.services.ldap.port }}
    targetPort: 389
    {{- with .Values.services.ldap.nodePort}}
    nodePort: {{ . }}
    {{-end}}
    protocol: TCP
    name: ldap
  - port: {{ .Values.services.ldaps.port }}
    targetport: 636
    {{- with .Values.services.ldaps.nodePort}}
    nodePort: {{ . }}
    {{-end}}
    protocol: TCP
    name: ldaps
  selector:
    {{- include "openldap.selectorLabels" . | nindent 4 }}
