replicaCount: 1

image:
  repository: theiaide/theia-full
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    # refs: https://kubernetes.github.io/ingress-nginx/examples/auth/basic/
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
  hosts:
  - host: theia.example.local
    paths: [ "/" ]
  tls:
  - secretName: example-tls
    hosts:
    - theia.example.local

storages:
  theia:
    path: <path to the directory>
    size: 50Gi
    hostname: example
  project:
    path: <path to the directory>
    size: 10Gi
    hostname: example
