replicaCount: 1
nameOverride: ""
fullnameOverride: ""

image:
  repository: osixia/openldap
  pullPolicy: IfNotPresent
  tag: "latest"

services:
  type: NodePort
  ldap:
    port: 389
    nodePort: 389
  ldaps:
    port: 636
    nodePort: 636

storages:
  data:
    size: 10Mi
    path: <path to data storage>
    hostname: <hostname>

admin:
  name: <admin name>
  password:
    secretName: <secret name for admin password>
    key: <secret key for admin password>

basedn: <base dn>

domain: <domain>
