apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "secret.fullname" . }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "secret.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "secret.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        volumeMounts:
        - name: home
          mountPath: /root
        - name: secret
          mountPath: /var/local/secret/data
        - name: backup1
          mountPath: "/var/local/secret/backup-1"
        - name: backup2
          mountPath: "/var/local/secret/backup-2"
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: {{ include "secret.storages.home.name" . }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "secret.storages.data.name" . }}
      - name: backup1
        persistentVolumeClaim:
          claimName: {{ include "secret.storages.backup1.name" . }}
      - name: backup2
        persistentVolumeClaim:
          claimName: {{ include "secret.storages.backup2.name" . }}
