apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "secret.storages.home.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.home.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "secret.storages.home.name" . }}
  local:
    path: {{ .Values.storages.home.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.home.hostname | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "secret.storages.data.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.data.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "secret.storages.data.name" . }}
  local:
    path: {{ .Values.storages.data.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.data.hostname | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "secret.storages.backup1.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.backup1.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "secret.storages.backup1.name" . }}
  local:
    path: {{ .Values.storages.backup1.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.backup1.hostname | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "secret.storages.backup2.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.backup2.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "secret.storages.backup2.name" . }}
  local:
    path: {{ .Values.storages.backup2.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.backup2.hostname | quote }}
