apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secret.storages.home.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.home.size | quote }}
  storageClassName: {{ include "secret.storages.home.name" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secret.storages.data.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.data.size | quote }}
  storageClassName: {{ include "secret.storages.data.name" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secret.storages.backup1.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.backup1.size | quote }}
  storageClassName: {{ include "secret.storages.backup1.name" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "secret.storages.backup2.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.backup2.size | quote }}
  storageClassName: {{ include "secret.storages.backup2.name" . }}
