apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "secret.storages.home.name" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "secret.storages.data.name" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "secret.storages.backup1.name" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "secret.storages.backup2.name" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
