apiVersion: v1
kind: Service
metadata:
  name: {{ include "secret.fullname" . }}
  labels:
    {{- include "secret.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ssh
    port: {{ .Values.service.port }}
    targetPort: 22
    {{- with .Values.service.nodePort}}
    nodePort: {{ . }}
    {{- end}}
    protocol: TCP
  selector:
    {{- include "secret.selectorLabels" . | nindent 4 }}
