replicaCount: 1

image:
  repository: localhost:32000/gitbk
  pullPolicy: IfNotPresent

storages:
  repos:
    path: <path to the repositories directory>
    size: 20Gi
    hostname: <hostname>

ssh:
  secretName: gitbk-ssh

args:
  sleep: 1
  interval: 3600
