replicaCount: 1

image:
  repository: localhost:32000/gitbk
  pullPolicy: IfNotPresent

storages:
  home:
    path: <path to the home directory>
    size: 1Gi
    hostname: <hostname>
  repos:
    path: <path to the repositories directory>
    size: 20Gi
    hostname: <hostname>

args:
  sleep: 1
  interval: 3600
