{{- if .Values.ingress.enabled -}}
{{- $svcName := include "code-server.services.http.name" . -}}
{{- $svcPort := .Values.services.http.port -}}
{{- $devName := include "code-server.services.dev.name" . -}}
{{- $devPort := .Values.services.dev.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.hosts.http.host | quote }}
    http:
      paths:
      {{- range .Values.ingress.hosts.http.paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $svcName }}
          servicePort: {{ $svcPort }}
      {{- end }}
  - host: {{ .Values.ingress.hosts.dev.host | quote }}
    http:
      paths:
      {{- range .Values.ingress.hosts.dev.paths }}
      - path: {{ . }}
        backend:
          serviceName: {{ $devName }}
          servicePort: {{ $devPort }}
      {{- end }}
{{- end }}
