apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "code-server.storages.share.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.share.size | quote }}
  storageClassName: {{ include "code-server.storages.share.name" . }}
