apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-server.fullname" . }}
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.http.type }}
  ports:
  - name: http
    port: {{ .Values.services.http.port }}
    targetPort: 8080
    protocol: TCP
  - name: dev
    port: {{ .Values.services.dev.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    {{- include "code-server.selectorLabels" . | nindent 4 }}
