apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "share.storages.data.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.data.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "share.storages.data.name" . }}
  local:
    path: {{ .Values.storages.data.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.data.hostname | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "share.storages.backup.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.backup.size | quote }}
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "share.storages.backup.name" . }}
  local:
    path: {{ .Values.storages.backup.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.backup.hostname | quote }}
