apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "share.storages.data.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.data.size | quote }}
  storageClassName: {{ include "share.storages.data.name" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "share.storages.backup.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.backup.size | quote }}
  storageClassName: {{ include "share.storages.backup.name" . }}
