apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gitbk.storages.repos.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storages.repos.size }}
  storageClassName: {{ include "gitbk.storages.repos.name" . }}
