replicaCount: 1

image:
  repository: localhost:32000/secret
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 22
  nodePort: 30200

storages:
  home:
    path: <path to the directory>
    size: 1Gi
    hostname: <hostname>
  data:
    path: <path to the directory>
    size: 10Gi
    hostname: <hostname>
  backup1:
    path: <path to the directory>
    size: 10Gi
    hostname: <hostname>
  backup2:
    path: <path to the directory>
    size: 10Gi
    hostname: <hostname>
