apiVersion: v1
kind: Service
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - name: ssh
    port: {{ .Values.service.port }}
    targetPort: 22
    {{- with .Values.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
    protocol: TCP
  selector:
    {{- include "collector.selectorLabels" . | nindent 4 }}
