apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "theia.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "theia.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        volumeMounts:
        - name: theia
          mountPath: /home/theia
        - name: project
          mountPath: /home/project
      volumes:
      - name: theia
        persistentVolumeClaim:
          claimName: {{ include "theia.storages.theia.name" . }}
      - name: project
        persistentVolumeClaim:
          claimName: {{ include "theia.storages.project.name" . }}
