apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "theia.storages.theia.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.theia.size | quote }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "theia.storages.theia.name" . }}
  local:
    path: {{ .Values.storages.theia.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.theia.hostname | quote }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "theia.storages.project.name" . }}
spec:
  capacity:
    storage: {{ .Values.storages.project.size | quote }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "theia.storages.project.name" . }}
  local:
    path: {{ .Values.storages.project.path | quote }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ .Values.storages.project.hostname | quote }}
