apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "theia.storages.theia.name" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "theia.storages.project.name" . }}
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
