apiVersion: v1
kind: Service
metadata:
  name: {{ include "theia.fullname" . }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 3000
    protocol: TCP
  selector:
    {{- include "theia.selectorLabels" . | nindent 4 }}
