apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spice-html5.fullname" . }}
  labels:
    {{- include "spice-html5.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spice-html5.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "spice-html5.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 5959
          protocol: TCP
        args: [ "{{ .Values.spice.host }}:{{ .Values.spice.port }}" ]
