apiVersion: v1
kind: Service
metadata:
  name: {{ include "spice-html5.fullname" . }}
  labels:
    {{- include "spice-html5.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5959
    protocol: TCP
    name: spice
  selector:
    {{- include "spice-html5.selectorLabels" . | nindent 4 }}
